sudo: required
dist: jammy

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
    
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev

install:
  - phpize
  - ./configure
  - make install

before_script:
  - echo "extension=proj.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini

script:
  make test
  - php phpng-proj.php

notifications:
  email:
    swen.zanon@geoglis.de
