language: php

php:
  - 7.0
  - nightly

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev

install:
  - phpize
  - ./configure
  - make install

before_script:
  - echo "extension=proj4.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini
