sudo: required
dist: trusty

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev/7.1

install:
  - phpize
  - ./configure
  - make install

before_script:
  - echo "extension = proj.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini

script:
  - php phpng-proj.php
